# Generated by Django 4.1.3 on 2022-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_finalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='candidate_four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='candidate_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='candidate_three',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalresult',
            name='candidate_two',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
