# Generated by Django 4.1.3 on 2022-11-26 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_rename_result_electionresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionresult',
            name='officer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
