# Generated by Django 4.1.3 on 2022-12-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_result_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalResult',
            fields=[
                ('result_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.result')),
            ],
            bases=('base.result',),
        ),
    ]
